import { Sora } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation/Navigation";
import Info from "@/components/Info/Info";
import Filters from "@/components/ui/Filters/Filters";
import Footer from "@/components/Footer/Footer";

export const sora_Thin = Sora({ subsets: ["latin"], weight: "100" });
export const sora_ExtraLight = Sora({ subsets: ["latin"], weight: "200" });
export const sora_Light = Sora({ subsets: ["latin"], weight: "300" });
export const sora_Regular = Sora({ subsets: ["latin"], weight: "400" });
export const sora_Semibold = Sora({ subsets: ["latin"], weight: "600" });
export const sora_Bold = Sora({ subsets: ["latin"], weight: "700" });
export const sora_ExtraBold = Sora({ subsets: ["latin"], weight: "800" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora_ExtraLight.className}>
        <div
          style={{
            paddingLeft: "8rem",
            paddingRight: "8rem",
          }}
        >
          <Navigation />
          <Info />
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignContent: " center",
              alignItems: "center",
            }}
          >
            <Filters
              style={{
                flexBasis: "20%",
                border: "1px solid red",
              }}
            />
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
